name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore ./PipelineTest_Api.sln

      - name: Build
        run: dotnet build ./PipelineTest_Api.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./PipelineTest_Api.sln --configuration Release --no-build
